### ISSUE TITLE
Generated zshrc provides wrong file path because of missplaced comment

### ISSUE THREAD

**Issue by cptalpdeniz** [zimfw/zimfw#280]
Description
-----------
After clean installation of linux, zsh and zim, and terminal is resourced, following error line comes up:
/home/xxxx/.zshrc:source:11: no such file or directory: /home/xxxx/.zim/init.zsh#

Steps to reproduce
------------------
Clean installation and reopening terminal

Possible Fixes (by end-user)
---------------------------
Change this line in .zshrc  
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh# Lines configured by zsh-newuser-install

to

[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh 
#Lines configured by zsh-newuser-install

This fixes the problem on my end (whenever I install zim regardless of the computer)

**Comment by collinforsyth** [comment]
In order to reproduce:
1. Remove all zsh files in`$HOME/` (I ran rm -rf ~/.z*)
2. Exit zsh and reopen

When you have zsh configured as your default terminal, [new-user-install](https://github.com/johan/zsh/blob/master/Functions/Newuser/zsh-newuser-install) will create a `~/.zshrc` file containing only this:

```
# Created by newuser for 5.4.2
```

It looks like when the original `zshrc` is added it appears to prepend the `template/zshrc` to the file causing the error.

Working on a PR right now.

**Comment by Eriner** [comment]
Simple (temporary) fix is to add a newline at the end of the copy/pasta blob.
