### ISSUE TITLE
suggestion: case-insensitive completion

### ISSUE THREAD

**Issue by Konfekt** [zimfw/zimfw#305]
How about including

```zsh
if is-at-least 4.3; then
  zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}'
else
  zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
fi
```
that allows for completing case-insensitively. For example, inside a folder that contains a single folder `RPM`, typing `cd ./r<tab>` would complete to `cd ./RPM` instead of doing nothing.

**Comment by ericbn** [comment]
We already have case-insensitive completion: https://github.com/zimfw/zimfw/blob/35c5daf791b295b007ab09a69324a132a225da59/modules/completion/init.zsh#L56. It has some issues already reported in #212 that we still didn't manage to solve completely, but it is case-insensitive.

Since you're reporting this and also #307, are you sure you have the completion module included in your .zimrc's zmodules array? The order in which it appears in the array is important. It should be one of the last ones, only followed by syntax-highlighting and history-substring-search, as we have in our template: https://github.com/zimfw/zimfw/blob/4b0a6f9c7cf2c2a9c73e3a253dc7b0a0a73853e0/templates/zimrc#L15

NOTES: We only support zsh >= 5.2, so testing for `is-at-least 4.3` will always result in true. And the matcher you're suggesting is smart-case (case-insensitive when pattern is lower case, case-sensitive otherwise), not case-insensitive.

**Comment by Konfekt** [comment]
Thank you, indeed I forgot to load the completion module. This solves it.
