### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by sQVe** [zimfw/zimfw#369]
Hey :wave:,

I just made the dive and **updated** my fork of `zimfw` to the **latest version and I was amazed**. The new design and implementation allows me to archive my fork fully and just keep the dotfiles. 

This framework is indispensable to me and my daily work so I just wanted to take the opportunity and give a **huge thank you to everyone involved**. A special thank you to @ericbn for driving version 1.0.0 forward.

Feel free to close this whenever :wink: 

:heart:

**Comment by ericbn** [comment]
Hey @sQVe, thats great feedback! Thank you for the kind words!

**Comment by jeffdupont** [comment]
Man, please let me know what you did to easily transition... my installation is screwed up badly. My custom prompt does not appear in the list `prompt -l`, my git shortcuts such as `gco -b my_new_branch` do not work... It seems to me that the changes and documentation are not backward compatible. My current computer is running on the commit `5387adb78e952fcb8cd8c7ccf43c6d4e293910fe` I realize it's old, but it work 100% for everything I needed and I know my pixelbook is running on a bit newer version as it was setup sometime in late 2018/early 2019...

**Comment by ericbn** [comment]
@jeffdupont, you can see the Zim "core" Changelog [here](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md).

There's no Changelog for the individual modules, and they all moved to separate repos. It's worth checking the README.md of [each module](https://github.com/zimfw/zimfw/wiki/Modules), as some changed in relation to the old Zim structure. The [git module](https://github.com/zimfw/git) for example now has a default prefix of `G` instead of `g`, and the prefix is configurable (so you can go back to `g` if you want, though the new prefix is worth giving a try, as it won't [clobber so many commands](https://github.com/zimfw/git/issues/2)).

**Comment by jeffdupont** [comment]
Thanks I'll have a look. I really liked Zim so I was disappointed when I
tried to set it up on a new machine and it had changed so drastically
compared.

**Comment by Bananaman** [comment]
@ericbn I wanted to thank you too, but didn't want to create a new ticket just for that, so I found this one.

Hello! :)

Thank you so freaking much for creating ZIM. I love everything about it. It's lean and clean, super fast and beautiful. I love how well organized and minimalistic the code is. I was always terrified of the bloated mess that is Oh My Zsh. And Prezto is cleaner but still a mess. Zim is exactly what I was searching for!

It's... perfect!

Wrote a thread to guide people towards Zim here:

https://www.reddit.com/r/linuxadmin/comments/rhg7wx/zsh_frameworks/

// Johnny

**Comment by ericbn** [comment]
@Bananaman, thanks a lot for spreading the love for Zim!
