### ISSUE TITLE
use zsh-defer

### ISSUE THREAD

**Issue by Konfekt** [zimfw/zimfw#372]
Just to leave for reference before it goes unnoticed, [zsh-defer](https://github.com/romkatv/zsh-defer) (by the author of [gitstatus](https://github.com/romkatv/gitstatus) mentioned in https://github.com/zimfw/zimfw/issues/336 ) speeds up starting zsh by running deferred commands after the prompt has shown up (and is idle).

**Comment by rjcoelho** [comment]
You suggest to zsh defer the zmodule calls ?

**Comment by ericbn** [comment]
@rjcoelho, zmodule is not called during startup, only when calling zimfw, so no need to defer that.

This should work:

1. Add zsh-defer as a module, but don't let Zim initialize it inside init.zsh:
   ```
   zmodule romkatv/zsh-defer -d
   ```
   and run `zimfw install`.

2. Initialize Zim with zsh-defer:
   ```
   source ${ZIM_HOME}/modules/zsh-defer/zsh-defer.plugin.zsh
   PS1='
   %F{135}%n%f at %F{166}%m%f in %F{118}%~%f
   %(!.#.$) '
   RPS1="%F{240}loading%f"
   setopt prompsubst
   if [[ ${ZIM_HOME}/init.zsh -ot ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
     # Update static initialization script if it's outdated, before sourcing it
     zsh-defer source ${ZIM_HOME}/zimfw.zsh init -q
   fi
   zsh-defer source ${ZIM_HOME}/init.zsh
   ```

Only issue I had with the above was that my PS1 (set by a prompt sourced by the init.zsh script) is updated on the current line, but after executing a command and getting a new prompt line, I get back the PS1 set above before the first call to zsh-defer, instead of my fulll prompt. Not sure what I am missing here.

**Comment by Konfekt** [comment]
Yes, somehow loading the prompt zmodule is not deferred correctly.

The only modules that significantly add startup time are those that add a per directory history such as https://github.com/gaoyifan/zsh-prioritize-cwd-history, but they are useful enough to justify it.

**Comment by ericbn** [comment]
I've also tried the following, that seemed to be more fit to how zsh-defer is intended to be used, but I got even more unstable results:

```
source ${ZIM_HOME}/modules/zsh-defer/zsh-defer.plugin.zsh
PS1='
%F{135}%n%f at %F{166}%m%f in %F{118}%~%f
%(!.#.$) '
RPS1="%F{240}loading%f"
setopt prompsubst
if [[ ${ZIM_HOME}/init.zsh -ot ${HOME}/.zimrc ]]; then
  zsh-defer source ${ZIM_HOME}/zimfw.zsh init -q
fi
while read zline; do
  zsh-defer -c "${zline}"
done < ${ZIM_HOME}/init.zsh
unset zline
```

In this case I also get "No such widget `history-substring-search-up'" when pressing UP, besides the prompt issue reported in the previous commit.

And in both cases, I noticed that also all that should be defined by the [environment](https://github.com/zimfw/environment) module (which is sourced inside init.zsh) is ignored. The history settings don't work (my history is empty instead of read from HISTFILE), and the setopt are not set (when I do setopt, I only get the default ones, and none of those additionally set by the module).

**Comment by romkatv** [comment]
> `while read zline; do`

Should this be `while IFS= read -r zline; do` ?

Also note that this loop will silently skip the last line if it doesn't end with `\n`. A more robust way to iterate over all non-empty would be this:

```zsh
for zline in ${(f)"$(<$ZIM_HOME/init.zsh)"}; do
  ...
done
```

> Yes, somehow loading the prompt zmodule is not deferred correctly.

`zsh-defer` executes commands from zle in function scope with `LOCAL_OPTIONS`, `LOCAL_PATTERNS` and `LOCAL_TRAPS` options. This breaks some some code. See https://github.com/romkatv/zsh-defer/blob/master/README.md#caveats. I don't know if this explains prompt zmodule breaking. If you find a caveat that isn't documented, please let me know.

**Comment by ericbn** [comment]
Thanks for the clarifications, @romkatv! This explains why the history, the setopt and the prompt configurations are not loaded with zsh-defer.

Just looking from the outside as a user, looks like p10k uses a different approach to load the whole .zshrc while displaying a temporary prompt and letting zle work. I haven't experienced any caveats with p10k.

**Comment by romkatv** [comment]
> Just looking from the outside as a user, looks like p10k uses a different approach to load the whole .zshrc while displaying a temporary prompt and letting zle work. I haven't experienced any caveats with p10k.

That's right. Powerlevel10k instant prompt, zsh-defer and zplugin turbo mode solve the same problem -- they remove Zsh startup lag. All of them have caveats but not equal amount thereof. zsh-defer has every caveat of instant prompt plus many more. Zplugin turbo mode has every caveat of zsh-defer plus a few more.

This is why I don't use zsh-defer myself. Since I'm using Powerlevl10k, I have access to instant prompt. It's easier to use (just add a few lines at the top of zshrc without changing anything else), much more reliable, and looks smoother (you get your regular prompt right away without having two different prompts).

**Comment by ericbn** [comment]
With the explained above by @romkatv, I think we should close this as "won't do".
