### ISSUE TITLE
How to pass `--depth=1` to `git clone`?

### ISSUE THREAD

**Issue by romkatv** [zimfw/zimfw#373]
Powerlevel10k lists installation instructions for 8 plugin managers. With 7 of them the git repository of powerlevel10k gets cloned with `--depth=1` to save space and time. How can I get `--depth=1` passed to `git clone` when using Zim?

For the reference, Zim installation instructions were added to Powerlevel10k in this commit: https://github.com/romkatv/powerlevel10k/commit/a50a336b64f6007cf99544c1ae62a4b359174783#diff-04c6e90faac2675aa89e2176d2eec7d8.

**Comment by lnicola** [comment]
I'm not sure if using `--depth 1` is a good idea. It breaks at times (e.g. when you force-push) and I recall at some point GitHub mentioned that clients doing a shallow clone followed by a pull were putting a lot of load on their servers.

**Comment by romkatv** [comment]
> I'm not sure if using `--depth 1` is a good idea. It breaks at times (e.g. when you force-push)

I don't force-push. Force-push breaks everyone, not just shallow clones.

> and I recall at some point GitHub mentioned that clients doing a shallow clone followed by a pull were putting a lot of load on their servers.

That sounds very surprising. Doesn't `git pull` send the same requests to the server regardless of whether the repo was cloned in full or with `--depth=1`? Do you have a reference?

Just to clarify, I'm not asking zim to be changed so that it uses `git clone --depth=1` by default. I'm also not trying to convince anyone that passing `--depth=1` is a good idea.

**Comment by lnicola** [comment]
Yeah, offering the option wouldn't hurt, it was more of a side-note.

I can't find that article, unfortunately.

**Comment by ericbn** [comment]
We can add a `--depth` option to the `zmodule` function. The option should then be passed to both `git clone` and `git fetch`, right?

**Comment by lnicola** [comment]
Apparently so, but see the comments in https://stackoverflow.com/a/23989289.

**Comment by ericbn** [comment]
@lnicola, so you mean that using the `--depth` option might break things in some scenarios?

I'm not a fan of `--depth` myself either. That's why I didn't include it as an option in the first release of zimfw.

I'm thinking of allowing the download of GitHub repos without using git (using curl or wget instead), in the lines of what [degit](https://github.com/Rich-Harris/degit) does. This would solve the problem that we're trying to solve here, plus it would make zimfw work in environments that don't have git installed.

Thoughts?

**Comment by lnicola** [comment]
> so you mean that using the --depth option might break things in some scenarios?

Yes, I think it does.

> I'm thinking of allowing the download of GitHub repos without using git (using curl or wget instead), in the lines of what degit does.

I'm partial to it. As prior art, I think most plugin managers I've used (mainly `vim` ones) use a `git` clone. Downloading the archive via HTTP might be a little nicer (still needs `unzip` though), but will be slower when updating a large repository. I think it's fine to go for the minimal thing that users are asking for (providing a way to pass `--depth 1`), because neither of the three choices is better than the other two.

**Comment by ericbn** [comment]
> neither of the three choices is better than the other two.

Which five choices are we talking about here? :blush:

**Comment by AndydeCleyre** [comment]
> I'm thinking of allowing the download of GitHub repos without using git (using curl or wget instead), in the lines of what [degit](https://github.com/Rich-Harris/degit) does.

That seems like a handy option to have. Would zim still upgrade modules installed this way?

**Comment by kaznovac** [comment]
i believe the most of users don't need git index in the zimfw modules (not even a shallow copy in their zimfw runtime)

i'm for the option in which `zmodule` prefers installation from the module's repository releases (same as the zimfw installs itself) by default; and `git` can be used as fallback when there are no releases available (or user insists on the concrete gitref [tag, branch, sha])

**Comment by ericbn** [comment]
@kaznovac, this is a good starting point for an improvement. Any idea how would we identify which asset from the release we should download?

Or maybe we don't even need to look into the releases, and instead download the tar file from the latest commit or HEAD of default branch, as [degit](https://github.com/Rich-Harris/degit) does. E.g. https://github.com/romkatv/powerlevel10k/archive/refs/heads/master.tar.gz. It would be great if we could do this without needing `git` at all (just `curl` or `wget`), as we cannot just use "master" and will need to figure out the actual branch name (can be "main" or something else).

Upgrading would be tricky in any of these cases -- it would probably need to delete the whole module and download the a new version of it.

**Comment by kaznovac** [comment]
@ericbn just updated my comment (was searching for the github's api doc for repository archiving)

there are some cases one might prefer releases over the archive - i.e. the artifact is built from the sources (like in zimfw's main repo)

it's worth investigating how does github create these archives (i could't find whether they respect the `export-ignore` attribute. are the archives verbose working trees or product of the `git archive`?)

i think that no changes to the `zmodule` api are needed: `-b`, and `-t` would do just fine
i'd leave for user to state the reference if desired, the aforementioned zipball api will use the default branch if gitref is omitted:
> If you omit :ref, the repository’s default branch (usually master) will be used

not sure about updates (downloading whole archives of modules on each update is definitely an overkill)
i think (don't hold my word for it, been some time since i've experimented with their api) github uses the http caching headers `etag`, `last-modified`, `cache-control`; might be worth investigating if we get [conditional http request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests) with `if-none-match` or `if-modifed-since` response `304 not modified` for the archive when it's not changed on the server

**Comment by ericbn** [comment]
Cool, @kaznovac! If there's a solution that:

* does not use git at all, so we can allow users that don't have git installed to also use Zim,
* can update modules without allways downloading everything, for example using http caching headers,
* it's simple for users to use, no need for additional options that expose the underlying mechanism details

then I think we'll have a good solution!

At a first glance, using release assets will be complex, as each project will release additional assets in a specific way and with specific names. And the "Source code" archives in each release are just an archive containing all files in the repo, pretty much what we would get using the [Download a repository archive (zip) GitHub API](https://docs.github.com/en/rest/reference/repos#download-a-repository-archive-zip), which BTW is great finding!

**Comment by ericbn** [comment]
@kaznovac, that's great research! It means the ideas we discussed earlier can really be implemented. For now, limited to GitHub and curl (hopefully we can adapt it to wget too).

**Comment by ericbn** [comment]
@kaznovac, @romkatv, I've committed the changes that include a Zim's "degit" tool that installs and updates modules as discussed above.

The usage is:
```
zmodule romkatv/powerlevel10k -u degit
```

This is not released yet, and might change before the next release, so let's not consider these as official installation instructions yet.

@kaznovac, if you and other contributors could play around with the current code from the master branch and let me know if you have any additional ideas before the next release, I would appreciate. Just copy https://raw.githubusercontent.com/zimfw/zimfw/master/zimfw.zsh over your `~/.zim/zimfw.zsh`.

**Comment by kaznovac** [comment]
@ericbn amazing work (just glanced the code), i'll gladly give it a run (need to find some time next week)...

**Comment by ericbn** [comment]
@romkatv, Zim 1.5.0 was just released, and with it our degit tool. I suggest that it should be used to setup powerlevel10k with Zim:
```
zmodule romkatv/powerlevel10k --use degit
```

**Comment by ericbn** [comment]
I was just checking how much degit is lighter and faster than git with the `romkatv/powerlevel10k` module. As of [today](https://github.com/romkatv/powerlevel10k/commit/6520323fdbc02190528ff3ded57361088d53cdfb):
* the complete repo had 83M, and
* the degit'ed module had 2.9M and was installed 43x times faster than what it took to clone the complete repo.

**Comment by romkatv** [comment]
Awesome! Thanks, Eric. I've verified that `zmodule romkatv/powerlevel10k --use degit` downloads 366KB from github.com and creates 2.1MB worth of files under `$ZIM_HOME`.
