### ISSUE TITLE
Unable to make HISTIGNORE works with zim

### ISSUE THREAD

**Issue by 2Belette** [zimfw/zimfw#376]
I am trying to use HISTIGNORE in my .zshrc but it ignores what I have put.
I want to avoid saving in the history everything related to shutdown/halt/poweroff/reboot to prevent hitting enter key to quickly.

I have tried
`export HISTIGNORE="/sbin/shutdown -r now:/sbin/poweroff:/sbin/halt:/sbin/poweroff:/sbin/hibernate"`

but shutdown -r now is kept in my .zshistory

I only see setopt `HIST_IGNORE_ALL_DUPS` on my .zshrc which is done by default by zim install but I don't think this is the cause of the issue.

Any idea?
Many thanks

**Comment by ericbn** [comment]
Hi. That's because HISTIGNORE is only understood by bash. Zsh has HISTORY_IGNORE, which does not behave exactly like HISTIGNORE in bash. See https://stackoverflow.com/a/38549502/2654518

Read the complete Zsh manual entry doing `man zshparam` and searching for HISTORY_IGNORE. Or read [here](http://zsh.sourceforge.net/Doc/Release/Parameters.html#Parameters-Used-By-The-Shell).

**Comment by 2Belette** [comment]
@ericbn many thanks now it make sense :)
