### ISSUE TITLE
How to install oh-my-zsh plugins or prezto modules

### ISSUE THREAD

**Issue by yanzhang0219** [zimfw/zimfw#380]
Hi,

Thank you first for this amazing plugin manager. I am new here. I am wondering how to install oh-my-zsh plugins and prezto modules. I just tried `zmodule ohmyzsh/ohmyzsh/tree/master/plugins/extract`, but it shows that it cannot find this repo. 

Thank you.

**Comment by ericbn** [comment]
Hi @yanzhang0219. Although zimfw is not initially intended to be used with plugins inside subdirectories, as is the case with ohmyzsh and prezto, you can manually initialize them with the --source option in zmodule. Ohmyzsh plugins generally also require you to add the plugin directory to fpath, and you can do it with the --fpath option in zmodule. We believe plugins are better maintained as separate repos, so we don't encourage the ohmyzsh or prezto approaches.

This is how it looks like:

```
zmodule ohmyzsh/ohmyzsh -f 'plugins/wd' -s 'plugins/wd/wd.plugin.zsh'
```
You can add multiple -s/--source and -f/--fpath options for initializing multiple plugins. 

And BTW we have our own archive module that can be used instead of the ohmyzsh's extract one.

**Comment by yanzhang0219** [comment]
Hi @ericbn. Thank you very much for your help. And I will definitely try the archive module shipped with zimfw.

**Comment by tombh** [comment]
Is this not included in the README in order to try to discourage its use?
