### ISSUE TITLE
HISTFILE not set correctly on Mac OSX 10.15 Catalina 

### ISSUE THREAD

**Issue by tpak** [zimfw/zimfw#386]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

In a terminal, run `zimfw info` and paste the output below:

```
zimfw version: 1.1.1 (previous commit is 6129062)
ZIM_HOME:      /Users/chris/.zim
Zsh version:   5.8
System info:   Darwin Chris-MacBook-Pro-15.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar 4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

also, I am using the latest zsh installed via Homebrew
$ zsh --version
zsh 5.8 (x86_64-apple-darwin19.3.0)

$ which zsh
/usr/local/bin/zsh
```

- gist of .zimrc:  standard .zimrc created by zim
- gist of .zshrc: standard zshrc created by zim 

Description
-----------
I upgraded yesterday from an older pre 1.x version of zimfw to v1.1.1 and noticed that my HISTFILE was misbehaving/misconfigured.

The HISTFILE option does not correctly get set.

The standard Mac configuration uses ~/.zsh_history - this is set in /etc/zshrc and zimfw attempts to override this in both the environments module as well as the history module. However, the option does not get set correctly. 

In both zimfw modules (environment and history) this is the syntax being used to try and set HISTFILE

: ${HISTFILE="${ZDOTDIR:-${HOME}}/.zhistory"}

This does not seem to work. But this syntax does. 

HISTFILE=${ZDOTDIR:-${HOME}}/.zhistory

Steps to reproduce
------------------
- Remove existing install of zimfw and any personalization from zsh files or temporarily remove them and install plain vanilla zimfw on MacOs 10.15 Catalina.
- Open a terminal
- echo $HISTFILE

**Comment by tpak** [comment]
I also thought that maybe the : ${ sytax was specifying to only set the HISTFILE option if it had not been previously set so I tried setting it in ~/.zshenv since that file gets read before ~/.zshrc but that did not work. I'm still relatively new to zsh and do very little scripting etc with it. I can't seem to find a good reference to what that syntax is doing at the beginning of the line.

**Comment by ericbn** [comment]
We set `HISTFILE` only if it was not previously set. It can be previously set by the user or by the OS, and there's no distinction between the two situations. You'll need to override the OS settings yourself in your `~/.zshrc` file.

In this case, overriding it in `~/.zshenv` does not work, because the OS' `/etc/zshrc` is sourced after it. Check:

|                |Interactive login |Interactive non-login|Script|
| --- | --- | --- | --- |
|/etc/zshenv     |    A      |    A      |  A   |
|~/.zshenv       |    B      |    B      |  B   |
|/etc/zprofile   |    C      |           |      |
|~/.zprofile     |    D      |           |      |
|/etc/zshrc      |    E      |    C      |      |
|~/.zshrc        |    F      |    D      |      |
|/etc/zlogin     |    G      |           |      |
|~/.zlogin       |    H      |           |      |
|&nbsp;          |           |           |      |
|&nbsp;          |           |           |      |
|~/.zlogout      |    I      |           |      |
|/etc/zlogout    |    J      |           |      |

(Source: https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/)

**Comment by tpak** [comment]
Well that is messy! Thanks for the info. I'll close this.
