### ISSUE TITLE
source .zimrc only if newer than init.zsh

### ISSUE THREAD

**Issue by Konfekt** [zimfw/zimfw#388]
The lines that are recommend to be added to the .`zshrc` at https://github.com/zimfw/install/blob/d4d894bbe8d67633dcdd2b1924759a272d78cb9e/src/templates/zshrc#L94

```zsh
# Initialize modules
if [[ ${ZIM_HOME}/init.zsh -ot ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  # Update static initialization script if it's outdated, before sourcing it
  source ${ZIM_HOME}/zimfw.zsh init -q
fi
source ${ZIM_HOME}/init.zsh
```

do not source `.zimrc` if its older than `init.zsh`. 

In case `init.zsh` is updated, why must the modification time of `.zimrc` also be updated?

**Comment by ericbn** [comment]
@Konfekt, it's intended to update `init.zsh` in case `.zimrc` was updated (not the other way around). This is, for example, for when you remove a module from `.zimrc` and expect it to be gone when you start a new shell.

I'm using `-ot` because I also want the `init.zsh` file to be updated/created in case it does not exist. According to the Conditional Expressions manual:

```
       file1 -ot file2
              true if file1 exists and is older than file2.
```

**Comment by Konfekt** [comment]
But then `.zimrc` is no longer sourced if `init.zsh` happens to be newer than `.zimrc`?

As far as I can see, `.zimrc` is only sourced at

```zsh
#  sh/zsh/.zim/zimfw.zsh (line 467)
init) _zimfw_source_zimrc && _zimfw_build ;;

#  sh/zsh/.zim/zimfw.zsh (lines 230-231)
_zimfw_source_zimrc() {
  local -r ztarget=${ZDOTDIR:-${HOME}}/.zimrc
```

I opened this issue because I did not notice for a while that `.zimrc` was no longer sourced and then found out it was because `init.zsh` was newer. 
This is not to be expected.

**Comment by ericbn** [comment]
`.zimrc` is not sourced during startup anymore, because it only should contain the module definitions. It's sourced by the `zimfw` CLI tool when you use it. Then `zimfw` builds the `init.zsh` script based on the module definitions there. That's why we want to make sure `init.zsh` is up to date by using the code above. 

Please check the Changelog.

**Comment by Konfekt** [comment]
Got it. I thought that all files in `$ZDOTDIR` were sourced, but now found that `.zimrc` forms the exception.

**Comment by ericbn** [comment]
The location of .zimrc didn't change when the new version of Zim was implemented. It went unnoticed that we could have thought of moving it to a different directory...

**Comment by Konfekt** [comment]
Yes, one could think of moving it to `~/.config/zimfw/` to distinguish clearly between the files sourced on ZSH startup and managed by zimfw.
