### ISSUE TITLE
.zcompdump

### ISSUE THREAD

**Issue by ppaa135** [zimfw/zimfw#548]
### Prerequisites

- [ ] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [ ] I've checked the zimfw [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [ ] I've checked the zimfw [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.

### Bug description

after use  "sudo pacman -Syu"  to upgrade my system，mention
“(anon):zcompile:22: can't open file: /home/N/.zcompdump”

### Steps to reproduce

1. ```
   cd ${$(mktemp -d):A} && \
       ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim && \
       curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh && \
       exec zsh
   ```
2. `Add more steps here ...`


### Current behavior

(anon):zcompile:22: can't open file: /home/N/.zcompdump

### Expected behavior

.zcompdump can be create

### zimfw info

_No response_

### Additional context

_No response_

**Comment by ericbn** [comment]
@ppaa135, did you install zimfw using our installation instructions (using curl or wget) or did you install the aur [zsh-zim-git](https://aur.archlinux.org/packages/zsh-zim-git) package?

**Comment by ppaa135** [comment]
@ericbn yes,I use curl to install zimfw

**Comment by ppaa135** [comment]
@ericbn what do you，like erro code or photo？

**Comment by ericbn** [comment]
Do you happen to have special characters in your home path? See https://stackoverflow.com/q/73493701/2654518

Also, have you checked if the permissions to the file are correct? You can try deleting the file and it should be recreated next time you restart your shell.

**Comment by ppaa135** [comment]
@ericbn The path does not contain special characters and the permissions are also correct, but after deleting this file and restarting the shell, the file is not recreated.

**Comment by ppaa135** [comment]
@ericbn After using the source ~/.zshrc command or updating the system kernel with pacman -Syu, I encounter the issue (anon):zcompile:22: can't open file: /home/N/.zcompdump. I can only resolve this problem by reinstalling zshfw, and this issue has occurred multiple times.

**Comment by ericbn** [comment]
@ppaa135, avoid using `source ~/.zshrc` to "restart" your shell configuration. This will have many undesired side effects. Use `exec zsh` instead.

**Comment by ppaa135** [comment]
@ericbn ok,i got it

**Comment by ppaa135** [comment]
@ericbn ut after updating the system with pacman -Syu, the same issue occurs when I reopen the terminal. How can I resolve this issue?

**Comment by ppaa135** [comment]
@ericbn But after updating the system with pacman -Syu, the same issue occurs when I reopen the terminal. How can I resolve this issue?

**Comment by ericbn** [comment]
Most likely this has nothing to do with zimfw itself. Let me know if I'm wrong.

**Comment by ppaa135** [comment]
@ericbn Okay, I will check it again after the next system update.

**Comment by ppaa135** [comment]
The issue has come up again, even after using 'exec zsh'. I'm at a loss as to where to start troubleshooting.

**Comment by ppaa135** [comment]
@ericbn The issue has come up again, even after using 'exec zsh'. I'm at a loss as to where to start troubleshooting.

**Comment by ericbn** [comment]
Hi. If the error is still `(anon):zcompile:22: can't open file: /home/N/.zcompdump` I'd try to investigate the different possibilities of zcompile being unable to open the file. Could be a permission issue?

Have you checked https://github.com/zimfw/zimfw/issues/44 or https://github.com/zsh-users/antigen/issues/632 ?

**Comment by fy-j** [comment]
> @ppaa135, avoid using `source ~/.zshrc` to "restart" your shell configuration. This will have many undesired side effects. Use `exec zsh` instead.

same error，after running source./zshrc, the same error is reported.

**Comment by PHZ20040126** [comment]
In fact，I have faced the same mistake, it reveal ```(anon):zcompile:28: can't open file: /home/p/.zcompdump```， Alse，there is no ```.zcompdump``` under  ```/home/p/```, but a file named ```.zcompdump.dat```   It‘s Strage. Are you have fixed the problem?

**Comment by ericbn** [comment]
Hi @PHZ20040126, if there’s no .zcompdump file, then this is good information to be able to debug the issue. This is not fixed yet.

**Comment by ericbn** [comment]
Fixed the completion module so zcompile is not called if something else failed during compinit. Run `zimfw update` to update.

**Comment by PHZ20040126** [comment]
However, I am using archlinux , and when I input `zimfw update`, it reported that `completion: Error during git merge`, it indicate that ` init.zsh` have been changed , what show I do to repair it ? If I should uninstall them all, and then reinstall them?

**Comment by PHZ20040126** [comment]
Atfer reinstall ,I find that the reason it indicates the `init.zsh` is that I changed it because of the info `compinit being called at /home/p/.zim/modules/completion/init.zsh:35
warning: completion was already initialized before completion module. Will call compinit again. See https://github.com/zimfw/zimfw/wiki/Troubleshooting#completion-is-not-working
warning: compinit being called again after completion module at /home/p/.zim/modules/completion/init.zsh:35
warning: completion was already initialized before completion module. Will call compinit again. See https://github.com/zimfw/zimfw/wiki/Troubleshooting#completion-is-not-working
warning: compinit being called again after completion module at /home/p/.zim/modules/completion/init.zsh:35
`that I followed the web `https://github.com/zimfw/zimfw/wiki/Troubleshooting#completion-is-not-working`
however I don't know whether this way drop into the warning "(anon):zcompile:22: can't open file: /home/user/.zcompdump"

**Comment by ericbn** [comment]
Now I see why you were greeting the “(anon):zcompile:22: can't open file: /home/user/.zcompdump" error. It was because you edited the completion/unit.zsh file and removed the compinit call from there. This causes the .zcompdump file to stop being generated.

Editing the completion/init.zsh file is not what the Troubleshooting wiki is instructing you to do. Also, this defies the purpose of using the completion module, which is exactly to handle the compinit call.

If you don’t know how to work with git to revert your charges, I suggest you use `zmodule completion —-use degit` instead.

**Comment by PHZ20040126** [comment]
However, if I don't edit `completion/init.zsh `, the warning `compinit being called at /home/p/.zim/modules/completion/init.zsh:35
compinit being called at /home/p/.zim/modules/completion/init.zsh:35
warning: completion was already initialized before completion module. Will call compinit again. See https://github.com/zimfw/zimfw/wiki/Troubleshooting#completion-is-not-working
warning: compinit being called again after completion module at /home/p/.zim/modules/completion/init.zsh:35
warning: completion was already initialized before completion module. Will call compinit again. See https://github.com/zimfw/zimfw/wiki/Troubleshooting#completion-is-not-working
warning: compinit being called again after completion module at /home/p/.zim/modules/completion/init.zsh:35`
would be shown every time 
It actually borrowed me. Painly~
