### ISSUE TITLE
merged file of template file and user file raise parse error

### ISSUE THREAD

**Issue by ghreyt** [zimfw/zimfw#94]
I think it needs to put newline between **template_file** and **user_file**
in installation part in **README.md**.

``` shell
setopt EXTENDED_GLOB
for template_file ( ${ZDOTDIR:-${HOME}}/.zim/templates/* ); do
  user_file="${ZDOTDIR:-${HOME}}/.${template_file:t}"
  touch ${user_file}
  ( print -rn "$(<${template_file})$(<${user_file})" >! ${user_file} ) 2>/dev/null
done
```

My initial **.zshrc** was like

``` shell
# comment about something
```

and installation loop above produces the **.zshrc** like

``` shell
... zim zshrc
...
# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
f# comment about something
```

, which raise parse error.

So I think it might be better to change printing line to put new line between template and user file
like below (or any better way).

``` shell
  ( print -rn "$(<${template_file})"$'\n'"$(<${user_file})" >! ${user_file} ) 2>/dev/null
```

**Comment by Eriner** [comment]
Yeah, that "script" blob is very finicky and prone to error. I wrote it to try to make installation easy, but without telling people to `curl xyz | zsh`, because I wanted the process to be transparent. With the move to the new organization and project structuring, this will be changed. I'll leave this issue open until I've finished that. Thanks for the report :+1:

**Comment by kaznovac** [comment]
#280 seems related
